name: main
on:
  pull_request:
    branches:
      - "master"
jobs:
  linting:
    name: Quality
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/linting.yml@main
    secrets: inherit
  unit_test:
    name: Quality
    needs: [linting]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/unit_test.yml@main
    secrets: inherit
  Sonar:
    name: SonarQube
    needs: [unit_test]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/sonarqube.yml@main
    with:
      DOWNLOAD_ARTIFACT: true
    secrets: inherit
