name: main quality
on:
  pull_request:
    branches:
      - 'master'
jobs:
  tf_quality:
    name: Quality
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/tf_quality.yml@main
    with:
      ROLE_ARN: arn:aws:iam::874706906285:role/App_cicd_github
    secrets: inherit
  tf_plan_integration:
    name: (integration) Tf plan
    needs: [tf_quality]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/tf_plan.yml@main
    with:
      APP_NODE_VERSION: 0.14.7-v0.28.7
      ADDRESS: ${{vars.CONTAINER_PRIVATE_REGISTRY}}
      ROLE_ARN: arn:aws:iam::874706906285:role/App_cicd_github
      TF_VAR_env: integration
      ENV_REPO: factory4_iadc-portal_iadc-portal-environments.git
    secrets: inherit