name: main_release
on:
  push:
    branches:
      - "master"

concurrency:
  group: ${{ github.ref }}
jobs:
  linting:
    name: Quality
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/linting.yml@main
    secrets: inherit
  unit_test:
    name: Quality
    needs: [linting]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/unit_test.yml@main
    secrets: inherit
  Sonar:
    name: SonarQube
    needs: [unit_test]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/sonarqube.yml@main
    with:
      DOWNLOAD_ARTIFACT: true
    secrets: inherit
  Release:
    needs: [linting, Sonar]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/release.yml@main
    with:
      COMPONENT_NAME: portal
    secrets: inherit
  Badges:
    needs: [release]
    uses: Sanofi-GitHub/fof-digital-foundation-release-strategy/.github/workflows/badges.yml@main
    with:
      UPDATE_COVERAGE_BADGE: true
    secrets: inherit
